### ISSUE TITLE
[golden_toolkit] Exception on widget with GlobalKey with multiple devices.

### ISSUE THREAD

**Issue by cirediew** [eBay/flutter_glove_box#132]
When doing a golden test on a widget with a `GlobalKey` an exception is thrown when tested on more than one device.

Success:
```dart
testGoldens('global Keys', (tester) async {
    final builder = DeviceBuilder()
      ..overrideDevicesForAllScenarios(devices: [Device.phone])
      ..addScenario(
        widget: Text(
          'abc',
          key: GlobalKey(debugLabel: 'myKey'),
        ),
      );
    await tester.pumpDeviceBuilder(builder);

    await screenMatchesGolden(tester, 'global_keys');
  });
```
Fail:
```dart
  testGoldens('global Keys', (tester) async {
    final builder = DeviceBuilder()
      ..overrideDevicesForAllScenarios(devices: [Device.phone, Device.tabletPortrait])
      ..addScenario(
        widget: Text(
          'abc',
          key: GlobalKey(debugLabel: 'myKey'),
        ),
      );
    await tester.pumpDeviceBuilder(builder);

    await screenMatchesGolden(tester, 'global_keys');
  });
```

Running ` flutter test test/widget_test/my_test.dart --update-goldens` will result in an exception thrown.

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.
The key [GlobalKey#63ac4 myKey] was used by multiple widgets. The parents of those widgets were:
- SizedBox(width: 375.0, height: 667.0, renderObject: RenderConstrainedBox#eb1df
relayoutBoundary=up7)
- SizedBox(width: 1024.0, height: 1366.0, renderObject: RenderConstrainedBox#57d26
relayoutBoundary=up7)
A GlobalKey can only be specified on one widget at a time in the widget tree.

When the exception was thrown, this was the stack:
#0      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:2774:13)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#2      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:2721:20)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#4      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:2717:35)
#5      BuildOwner._debugVerifyGlobalKeyReservation (package:flutter/src/widgets/framework.dart:2782:6)
#6      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2841:11)
#7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2922:8)
#8      AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1148:19)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#12     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:995:9)
#15     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#16     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:982:27)
#17     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:548:22)
#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#21     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:545:27)
#22     _pumpAppWidget (package:golden_toolkit/src/testing_tools.dart:128:16)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.
The key [GlobalKey#63ac4 myKey] was used by multiple widgets. The parents of those widgets were:
- SizedBox(width: 375.0, height: 667.0, renderObject: RenderConstrainedBox#eb1df
relayoutBoundary=up7)
- SizedBox(width: 1024.0, height: 1366.0, renderObject: RenderConstrainedBox#57d26
relayoutBoundary=up7)
A GlobalKey can only be specified on one widget at a time in the widget tree.

When the exception was thrown, this was the stack:
#0      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:2774:13)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#2      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:2721:20)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#4      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:2717:35)
#5      BuildOwner._debugVerifyGlobalKeyReservation (package:flutter/src/widgets/framework.dart:2782:6)
#6      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2841:11)
#7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2922:8)
#8      AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1148:19)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#12     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:995:9)
#15     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#16     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:982:27)
#17     WidgetTester.pump.<anonymous closure> (package:flutter_test/src/widget_tester.dart:608:53)
#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#21     WidgetTester.pump (package:flutter_test/src/widget_tester.dart:608:27)
#22     _pumpAppWidget (package:golden_toolkit/src/testing_tools.dart:131:16)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by mZadorskii** [comment]
Each scenario is recreating your widget under test and it's keys as well .

Global keys can not be reused, please read Flutter documentation.
Simply replace your global key with regular Key().

**Comment by cirediew** [comment]
Unfortunately changing the global keys to normal keys is not an option. It is for the example, just not for my real code. I'm using this package https://pub.dev/packages/showcaseview which requires GlobalKeys.

**Comment by coreysprague** [comment]
I don't think global keys in widgets are compatible with DeviceBuilder. The DeviceBuilder API was a community contribution that I don't personally use in my projects, but it works my putting multiple copies of the same widget in a composed widget.

I think you would be better off using multiple ```screenMatchesGolden``` or ```multiScreenGolden()``` assertions in your test.

**Comment by coreysprague** [comment]
It seems like a bug that it still throws this assertion even when you try to force only a single device though

**Comment by cirediew** [comment]
@coreysprague Using `multiScreenGolden` works. Thank you!

**Comment by coreysprague** [comment]
Great. I'll leave this issue open to at least update the documentation with a disclaimer
