### ISSUE TITLE
[golden_toolkit] Goldens for different devices have different time advance

### ISSUE THREAD

**Issue by cyrax111** [eBay/flutter_glove_box#146]
I made a simple project just entered :
`flutter create golden`

and added FutureBuilder
```
FutureBuilder(
  future: Future<int>.delayed(
      const Duration(milliseconds: 150), () => 1),
  builder: (context, snapshot) {
    if (snapshot.hasData) {
      return Container(
          color: Colors.orange, width: 100, height: 100);
    }
    return const CircularProgressIndicator();
  },
)
```

The behavior is the first 150 milliseconds is showed CircularProgressIndicator then an orange container.

I wrote follow golden test:
```
testGoldens('Counter golden test', (WidgetTester tester) async {
  await loadAppFonts();

  await tester.pumpWidgetBuilder(const MyHomePage(title: 'Title'));

  await multiScreenGolden(
    tester,
    'my_home_page',
    devices: [Device.phone, Device.iphone11, Device.tabletLandscape],
    customPump: (tester) async {},
    deviceSetup: (device, tester) async {
      await tester.pump(const Duration(milliseconds: 50));
    },
  );

  await tester.pump(const Duration(hours: 1));
});
```

and have got follow result:
Device.phone
![my_home_page phone](https://user-images.githubusercontent.com/24819874/149085298-64873695-63a7-446a-8480-4e0c67616e27.png)

Device.iphone11
![my_home_page iphone11](https://user-images.githubusercontent.com/24819874/149085291-d19886a3-a8a9-4d72-99bb-24e27bf65107.png)

Device.tabletLandscape
![my_home_page tablet_landscape](https://user-images.githubusercontent.com/24819874/149085302-1050d056-e254-4ee9-9a73-c1ba305b7e80.png)

Despite only one `tester.pump` I have different time advances.

I expected the same picture on all devices like on Device.phone.

**Comment by coreysprague** [comment]
the device setup function runs in between resizing for each device. So in this case, 50ms are pumped before Device.phone, 100ms are pumped before iphone11, and 150ms are pumped before the tablet landscape golden. In other words, what you are seeing is working as intended.

if your deviceSetup function does not advance time, I would expect all of the screen variations to be in the same state.

**Comment by cyrax111** [comment]
if I leave deviceSetup empty and put the pump in customPump the result will be the same:

```
  await multiScreenGolden(
    tester,
    'my_home_page',
    devices: [Device.phone, Device.iphone11, Device.tabletLandscape],
    customPump: (tester) async {
      await tester.pump(const Duration(milliseconds: 50));
    },
    deviceSetup: (device, tester) async {
    },
  );
```

**Comment by coreysprague** [comment]
I think the customPump (I _HATE_ that name) will similarly be called in between each golden as well.

What are you trying to do, are you trying to pump 50ms and THEN capture a golden for multiple devices? If so, just move your ```await tester.pump(const Duration(milliseconds: 50));``` to be before you call ```await multiScreenGolden```

**Comment by coreysprague** [comment]
or you could do something like:

```
await tester.pump(const Duration(milliseconds: 50));
await multiScreenGolden(tester, 'loading' ... )


await tester.pump(const Duration(milliseconds: 100));
await multiScreenGolden(tester, 'loaded' ... );
```

**Comment by cyrax111** [comment]
I need to rid from any pumps between each golden. If I leave `deviceSetup` and `customPump` empty and move my pump before `multiScreenGolden` I have got an error.

**Comment by cyrax111** [comment]
the error:
```
00:04 +0: Counter golden test                                                                                           
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
'package:flutter_test/src/_matchers_io.dart': Failed assertion: line 28 pos 10:
'!renderObject.debugNeedsPaint': is not true.

When the exception was thrown, this was the stack:
#2      captureImage (package:flutter_test/src/_matchers_io.dart:28:10)
#3      MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:82:21)
#4      _expect (package:test_api/src/expect/expect.dart:101:26)
#5      expectLater (package:test_api/src/expect/expect.dart:62:5)
#6      expectLater (package:flutter_test/src/widget_tester.dart:492:23)
#7      compareWithGolden (package:golden_toolkit/src/testing_tools.dart:290:9)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from class _AssertionError and package:stack_trace)

The test description was:
  Counter golden test
════════════════════════════════════════════════════════════════════════════════════════════════════
00:04 +0 -1: Counter golden test [E]                                                                                    
  Test failed. See exception logs above.
  The test description was: Counter golden test
```

For easely access I made a repository [https://github.com/cyrax111/golden_test](https://github.com/cyrax111/golden_test)

**Comment by coreysprague** [comment]
I'll try to look at it today. I suspect you will still need a pump, but with Duration(milliseconds: 0)

**Comment by cyrax111** [comment]
Thank you! I think one pump without duration don't help me unfortunately as well.
You can check the tag v2 for it.

**Comment by cyrax111** [comment]
@coreysprague you can try this [https://github.com/cyrax111/golden_test/tree/v2](https://github.com/cyrax111/golden_test/tree/v2)

**Comment by coreysprague** [comment]
What if you do this?

![image](https://user-images.githubusercontent.com/5420324/151025556-ad2f103d-e1a5-4d6c-836d-4276f4d69caa.png)


Obviously the counts are wrong -- in order to multiScreenGoldens to be captured, the widgets have to be rebuilt, which in your code will always increment the counter...

But:
![image](https://user-images.githubusercontent.com/5420324/151025696-d41c2970-4028-4945-b26b-f75f0b974474.png)
![image](https://user-images.githubusercontent.com/5420324/151025726-34106f77-5ed5-48e9-a079-38cb1defcc78.png)
![image](https://user-images.githubusercontent.com/5420324/151025747-1764c2dd-1913-41f3-a95d-84cf180d1a11.png)

**Comment by coreysprague** [comment]
@cyrax111  -- sorry for the delay. Been slammed at work

**Comment by cyrax111** [comment]
@coreysprague thank you for your answer!!

**Comment by cyrax111** [comment]
> in order to multiScreenGoldens to be captured, the widgets have to be rebuilt

I think I need a little bit another behavior. I want to separate devices in order to make them independent.

I added this feature here [https://github.com/cyrax111/golden_test/tree/v3](https://github.com/cyrax111/golden_test/tree/v3).
There is `testDeviceGoldens` in `test_device_goldens.dart` file.
And you can run `widget_separate_devices_test.dart` for test.

If you want I can make PR.

Result:
![main iphone11](https://user-images.githubusercontent.com/24819874/151544037-f55d39d8-f01a-4c24-82f2-fa0b807aa50d.png)
![main phone](https://user-images.githubusercontent.com/24819874/151544042-5cb70fa6-0209-42e2-9310-61272baef6fe.png)
![main tablet_landscape](https://user-images.githubusercontent.com/24819874/151544044-e0d23eca-135b-45f8-991c-ce056e5f1ff9.png)
